<?php

function cptui_register_my_cpts_testmysite() {

	/**
	 * Post Type: Test my site.
	 */

	$labels = array(
		"name" => __( "Test my site", "understrap-child" ),
		"singular_name" => __( "Test my site", "understrap-child" ),
		"menu_name" => __( "Test My Site Report", "understrap-child" ),
		"all_items" => __( "All Test My Site Reports", "understrap-child" ),
		"add_new" => __( "Add New", "understrap-child" ),
		"add_new_item" => __( "Add New Report", "understrap-child" ),
		"edit_item" => __( "Edit Report", "understrap-child" ),
		"new_item" => __( "New Report", "understrap-child" ),
		"view_item" => __( "View Report", "understrap-child" ),
		"view_items" => __( "View Reports", "understrap-child" ),
		"search_items" => __( "Search Report", "understrap-child" ),
		"not_found" => __( "No Reports found.", "understrap-child" ),
		"not_found_in_trash" => __( "No Reports found in trash", "understrap-child" ),
		"filter_items_list" => __( "Filter Test My Site Report List", "understrap-child" ),
		"items_list_navigation" => __( "Test My Site Report Navigation List", "understrap-child" ),
		"items_list" => __( "Test My Site Reports", "understrap-child" ),
		"name_admin_bar" => __( "Test My Site Report", "understrap-child" ),
	);

	$args = array(
		"label" => __( "Test my site", "understrap-child" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"delete_with_user" => false,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "testmysite", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title" ),
	);

	register_post_type( "testmysite", $args );
}

add_action( 'init', 'cptui_register_my_cpts_testmysite' );

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f02b96b53051',
	'title' => 'Test My Site Report',
	'fields' => array(
		array(
			'key' => 'field_5fe184b840e4f',
			'label' => 'Company Information',
			'name' => 'company_information',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_5f02b984b4350',
			'label' => 'Friendly name',
			'name' => 'friendly_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter friendly name',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f02bb47b4351',
			'label' => 'Company name',
			'name' => 'company_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter company name',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f02bb93b4352',
			'label' => 'Company website',
			'name' => 'company_website',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter company website',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f02bdacb4353',
			'label' => 'Company image',
			'name' => 'company_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => 400,
			'max_height' => 200,
			'max_size' => '',
			'mime_types' => 'jpeg, jpg, png, gif',
		),
		array(
			'key' => 'field_5f02bf14b4354',
			'label' => 'Company image alt tag',
			'name' => 'company_image_alt_tag',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f02bf5bb4355',
			'label' => 'Image background',
			'name' => 'image_background',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'blue' => 'Blue',
				'white' => 'White',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f02c01eb4356',
			'label' => 'Scope',
			'name' => 'scope',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5f02c073b4357',
					'label' => 'Website',
					'name' => 'website',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter website',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f02c09cb4358',
					'label' => 'Date',
					'name' => 'date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5f02c117b4359',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'uploadedTo',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 400,
					'max_height' => 200,
					'max_size' => '',
					'mime_types' => 'jpeg, jpg, png, gif',
				),
				array(
					'key' => 'field_5f02c1f1b435a',
					'label' => 'Logo alt tag',
					'name' => 'logo_alt_tag',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter logo alt text',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5f02c950b435b',
			'label' => 'Eval Details',
			'name' => 'eval_details',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6149dd13d3a3d',
					'label' => 'Site Status',
					'name' => 'site_status',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'not accessible' => 'Not Accessible',
						'needs improvement' => 'Needs Improvement',
						'accessible' => 'Accessible',
					),
					'default_value' => array(
						0 => 'not accessible',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6149e22275bab',
					'label' => 'Site score',
					'name' => 'site_score',
					'type' => 'text',
					'readonly' => 1,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f02c9acb435d',
					'label' => 'Summary',
					'name' => 'summary',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_5f02ca6ab435e',
			'label' => 'Usability Details',
			'name' => 'usability_details',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5f02caabb435f',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Usability Detail',
			'sub_fields' => array(
				array(
					'key' => 'field_5f02caabb435f',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f02cb32b4360',
					'label' => 'Note',
					'name' => 'note',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter note',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5f02cc82b4361',
			'label' => 'Accessibility Details',
			'name' => 'accessibility_details',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5f02cccfb4362',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Accessibility Detail',
			'sub_fields' => array(
				array(
					'key' => 'field_5f02cccfb4362',
					'label' => 'CSS selector',
					'name' => 'css_selector',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter css selector',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f02cd4ab4363',
					'label' => 'WCAG definition',
					'name' => 'wcag_definition',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f02cd93b4364',
					'label' => 'Notes',
					'name' => 'notes',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter notes',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
				),
			),
		),
		array(
			'key' => 'field_5f02ce87b4365',
			'label' => 'Recommendations',
			'name' => 'recommendations',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5f02cee7b4366',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Recommendation',
			'sub_fields' => array(
				array(
					'key' => 'field_5f02cee7b4366',
					'label' => 'Recommendation',
					'name' => 'recommendation',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5f02d14ab4369',
			'label' => 'Hide',
			'name' => 'hide',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testmysite',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;

?>